version: '3.9.3'
services:
  jekyll:
    container_name: my-blog
    image: jekyll/jekyll:3.9.3
    ports:
      - 80:4000
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/.cache/bundle:/usr/local/bundle
    command: jekyll serve